project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "../"
#preserve_hierarchy: true
files: [
  {
    source: "/*.properties",
    translation: "/src/main/resources/assets/viaproxy/language/%locale_with_underscore%.properties"
  }
]
